# Generated by Django 4.2.1 on 2023-06-19 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='Телефон')),
                ('phone_code', models.CharField(max_length=10, verbose_name='Код оператора')),
                ('tags', models.CharField(max_length=127, verbose_name='Тэги')),
                ('t_zone', models.DateTimeField(verbose_name='часовой пояс')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='SendList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(verbose_name='Начало рассылки')),
                ('send_text', models.TextField(max_length=255, verbose_name='Текст')),
                ('filter', models.TextField(max_length=127, verbose_name='Фильтры')),
                ('date_end', models.DateTimeField(verbose_name='Конец рассылки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_send', models.DateTimeField(auto_now_add=True, verbose_name='Начало рассылки')),
                ('status_sent', models.BooleanField(blank=True, verbose_name='Доставлено')),
                ('clients', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='message', to='sender.clients')),
                ('sendlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='message', to='sender.sendlist')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
