# Generated by Django 4.2.1 on 2023-07-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='time_zone',
            field=models.CharField(max_length=20, verbose_name='часовой пояс'),
        ),
    ]
