# Generated by Django 4.2.1 on 2023-07-13 13:32

from django.db import migrations
import sender.models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='t_zone',
            field=sender.models.MyDateTimeField(verbose_name='часовой пояс'),
        ),
    ]
