# Generated by Django 4.2.1 on 2023-07-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0002_alter_clients_t_zone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='t_zone',
            new_name='time_with_zone',
        ),
    ]
